# Generated by Django 3.1.5 on 2021-02-15 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='regiseter_date',
            new_name='register_date',
        ),
    ]
